package com.myself.demo.utlis

import com.myself.demo.model.Anser
import com.myself.demo.model.Question

class Constants {

    fun getQuestion(): ArrayList<Question> {

        val questionsList = ArrayList<Question>()
        val ansersList1 = ArrayList<Anser>()
        val ansersList2 = ArrayList<Anser>()

        ansersList1.add(Anser(1,5,"دائما"))
        ansersList1.add(Anser(2,4,"غالبا"))
        ansersList1.add(Anser(3,3,"أحياناً"))
        ansersList1.add(Anser(4,2,"نادرا"))
        ansersList1.add(Anser(5,1,"إطلاقاً"))

        ansersList2.add(Anser(1,1,"دائما"))
        ansersList2.add(Anser(2,2,"غالبا"))
        ansersList2.add(Anser(3,3,"أحياناً"))
        ansersList2.add(Anser(4,4,"نادرا"))
        ansersList2.add(Anser(5,5,"إطلاقاً"))

        val que1 = Question(1,"إني راض عن نتائجي المدرسية.",ansersList1)
        val que2 = Question(2,"والداي يتوقعان مني أكثر مما أستطيع.",ansersList2)
        val que3 = Question(3,"يزعجني النقد الموجه إلي من الآخرين.",ansersList2)
        val que4 = Question(4,"أجد أنني قادر على تقديم رأي مناسب إذا ما استشرت.",ansersList1)
        val que5 = Question(5,"أشعر أنني أستطيع التحدث أمـام مجموعـة مـن النـاس دون حـرج أو ارتباك.",ansersList1)
        val que6 = Question(6,"كثيراً ما أفشل في تكوين انطباعـات جيدة علي لدى الآخرين.",ansersList2)
        val que7 = Question(7,"أعتقد أن لـدي أفكـار جـيـدة مقارنة بزملائي.",ansersList1)
        val que8 = Question(8,"أستطيع مواجهة المواقف الجديدة أو غير المألوفة بكفاءة.",ansersList1)
        val que9 = Question(9,"كثيراً مـا أشـعـر بعـدم الـرضـي عـن مستوى أدائي في الأعمال المطلوبة مني في البيت أو في المدرسة.",ansersList2)
        val que10 = Question(10,"إن نجاح الآخرين من حولي يذكرني بفشلي",ansersList2)
        val que11 = Question(11,"أشعر أن هناك أموراً كثيرة في الحياة لا أستطيع مواجهتها.",ansersList2)
        val que12 = Question(12,"يثق الآخرين بقدرتي على إعطاء حل يناسب المشاكل التي تعترضهم.",ansersList1)
        val que13 = Question(13,"أجد في نفسي الكفـاءة للقيام بأعمال تحتاج إلى تخطيط وتنظيم.",ansersList1)
        val que14 = Question(14,"يشعرني معلمي بأني غير كفؤ.",ansersList2)
        val que15 = Question(15,"إذا كان لدي ما أقوله فإنني أقوله دون تردد.",ansersList1)
        val que16 = Question(16,"إنني أفهم حقيقة نفسي.",ansersList1)
        val que17 = Question(17,"إنني خجول في الغالب.",ansersList2)
        val que18 = Question(18,"تثير أفكاري تقدير الآخرين وإعجابهم.",ansersList1)
        val que19 = Question(19,"كثيراً ما أندم على ما أفعل.",ansersList2)
        val que20 = Question(20,"أفضّل نفسي على الآخرين في المواقف التي تواجهني.",ansersList1)
        val que21 = Question(21,"أعرف ما يجب أن أقوله للناس.",ansersList1)
        val que22 = Question(22,"تختلط عليّ أمور حياتي من حين إلى آخر",ansersList2)
        val que23 = Question(23,"أشعر أن هناك مواقف كثيرة أفقد فيها الثقة بنفسي.",ansersList2)
        val que24 = Question(24,"لا يعيرني الناس كثيراً إهتمامهم.",ansersList2)
        val que25 = Question(25,"ما أعمله هو العمل الصحيح.",ansersList1)
        val que26 = Question(26,"أستطيع أخذ زمام المبادرة في المواقف الاجتماعية.",ansersList1)
        val que27 = Question(27,"ينتابني الشعور بالكآبة عنـد مواجهـة موقف مشکل.",ansersList2)
        val que28 = Question(28,"يصعب علي أن أتصرف باستقلالية وأعمل ما يراه الآخرون مناسباً.",ansersList2)
        val que29 = Question(29,"أشعر بأنني محبوب لدى الآخرين.",ansersList1)
        val que30 = Question(30,"كثيراً ما تخليت عن إنجاز بعض الأعمال لشعوري بعدم القدرة على إنجازها",ansersList2)
        val que31 = Question(31,"انهزم في مواقف الجدل والنقاش بسهولة.",ansersList2)
        val que32 = Question(32,"كثيراً ما ينتابني القلق دون سبب.",ansersList2)
        val que33 = Question(33,"أشعر بأنني ذكي.",ansersList1)
        val que34 = Question(34,"أنا ميال للاستسلام بسرعة عندما تتعقـد الأمور.",ansersList2)
        val que35 = Question(35,"عندما يكون لـدي عـدد مـن الأمـور لاختار بينهـا فـإنني أجـد صعوبة في الاختيار.",ansersList2)
        val que36 = Question(36,"أشعر أنني لا أستطيع أن أصـل إلى مستوى النجاح الذي حققـه بعـض الناس الذين أعرفهم.",ansersList2)
        val que37 = Question(37,"كثيراً ما أحس بأن حياتي صعبة.",ansersList1)
        val que38 = Question(38,"أشعر بالحرج بسهولة.",ansersList2)

        questionsList.add(que1)
        questionsList.add(que2)
        questionsList.add(que3)
        questionsList.add(que4)
        questionsList.add(que5)
        questionsList.add(que6)
        questionsList.add(que7)
        questionsList.add(que8)
        questionsList.add(que9)
        questionsList.add(que10)
        questionsList.add(que11)
        questionsList.add(que12)
        questionsList.add(que13)
        questionsList.add(que14)
        questionsList.add(que15)
        questionsList.add(que16)
        questionsList.add(que17)
        questionsList.add(que18)
        questionsList.add(que19)
        questionsList.add(que20)
        questionsList.add(que21)
        questionsList.add(que22)
        questionsList.add(que23)
        questionsList.add(que24)
        questionsList.add(que24)
        questionsList.add(que25)
        questionsList.add(que26)
        questionsList.add(que27)
        questionsList.add(que28)
        questionsList.add(que29)
        questionsList.add(que30)
        questionsList.add(que31)
        questionsList.add(que32)
        questionsList.add(que33)
        questionsList.add(que34)
        questionsList.add(que35)
        questionsList.add(que36)
        questionsList.add(que37)
        questionsList.add(que38)

        return questionsList
    }
}